DEFAULT_DATA_DIR = "./mnemosyne_data"
SQLITE_DB_NAME = "mnemosyne.db"
ZVEC_COLLECTION_DIR = "zvec_notes"
ZVEC_COLLECTION_NAME = "mnemosyne_notes"

EMBEDDING_MODEL = "nomic-ai/nomic-embed-text-v1.5"
EMBEDDING_DIM = 384
EMBEDDING_QUERY_PREFIX = "search_query: "
EMBEDDING_DOC_PREFIX = "search_document: "

RRF_K = 60
SCHEMA_VERSION = 1

PROVENANCE_ORGANIC = "organic"
PROVENANCE_AGENT_PROMPTED = "agent_prompted"
PROVENANCE_USER_CONFIRMED = "user_confirmed"
PROVENANCE_INFERRED = "inferred"

NOTE_TYPE_OBSERVATION = "observation"
NOTE_TYPE_INFERENCE = "inference"

DURABILITY_PERMANENT = "permanent"
DURABILITY_CONTEXTUAL = "contextual"
DURABILITY_EPHEMERAL = "ephemeral"

LINK_TYPES = ["semantic", "causal", "temporal", "contradicts", "supports", "derived_from"]

DEFAULT_CONFIDENCE_OBSERVATION = 0.8
DEFAULT_CONFIDENCE_INFERENCE = 0.6
DEFAULT_CONFIDENCE_USER_SET = 1.0
DEFAULT_EMOTIONAL_WEIGHT = 0.5

# Deriver API (Phase 2)
NOUSRESEARCH_BASE_URL = "https://inference-api.nousresearch.com/v1"
NOUSRESEARCH_MODEL = "deepseek/deepseek-v3.2"
DERIVER_EXTRACT_TEMPERATURE = 0.1
DERIVER_SCORE_TEMPERATURE = 0.1
DERIVER_MAX_RETRIES = 3
DERIVER_RETRY_DELAYS = [1.0, 2.0, 4.0]
WORKER_POLL_INTERVAL = 2.0

# Phase 3: Retrieval scoring
DECAY_LAMBDA_BASE = 0.1
DECAY_IMPORTANCE_FACTOR = 0.8
DECAY_ACCESS_BOOST = 0.15
DECAY_MEMORY_THRESHOLD = 100        # disabled below this count
DECAY_RAMP_MAX = 1000               # full effect at this count
DECAY_HIGH_IMPORTANCE_THRESHOLD = 0.7
DECAY_HIGH_IMPORTANCE_FLOOR = 0.3

PROVENANCE_WEIGHTS = {
    "organic": 1.0,
    "user_confirmed": 0.8,
    "agent_prompted": 0.5,
    "inferred": 0.3,
}

SURFACING_FATIGUE_RATE = 0.1

INFERENCE_DISCOUNT = 0.7            # inferences weighted lower than observations

MMR_SIMILARITY_THRESHOLD = 0.90

RETRIEVAL_FTS_LIMIT = 30
RETRIEVAL_VECTOR_LIMIT = 30
RETRIEVAL_FINAL_LIMIT = 10

# --- Phase 4: Intelligence layer ---

# ColBERT reranking
COLBERT_MODEL = "answerdotai/answerai-colbert-small-v1"
COLBERT_RERANK_CANDIDATES = 30
COLBERT_TOP_N = 10

# A-MEM link generation
LINK_SIMILARITY_THRESHOLD = 0.75
LINK_MAX_CANDIDATES = 10
LINK_DEFAULT_STRENGTH = 0.5
LINK_STRENGTH_FROM_SIMILARITY = True

# Link expansion in retrieval
LINK_EXPANSION_DEPTH = 1
LINK_EXPANSION_MAX = 5
LINK_EXPANSION_TOP_SEEDS = 5

# Static profile
PROFILE_MAX_FACTS = 30
PROFILE_MAX_TOKENS = 400
PROFILE_SECTIONS = ["identity", "professional", "communication_style", "relationships"]
PROFILE_MIN_NOTES = 5
PROFILE_REGENERATE_INTERVAL_HOURS = 24

# --- Phase 5: Background processes ---

# ColBERT token dimensions
COLBERT_TOKEN_DIM = 96

# Batch dedup
DEDUP_COSINE_THRESHOLD = 0.85
DEDUP_MIN_CLUSTER_SIZE = 2

# Dreamer — Gemini Batch API
GEMINI_MODEL = "gemini-3-flash-preview"
DREAMER_TEMPERATURE = 0.3
DREAMER_POLL_INTERVAL = 30.0
DREAMER_MAX_POLL_TIME = 86400
DREAMER_LINK_TEMPERATURE = 0.3
DREAMER_PATTERN_TEMPERATURE = 0.3
DREAMER_CONTRADICTION_TEMPERATURE = 0.1
DREAMER_PROFILE_TEMPERATURE = 0.1

# MAGMA graph names
ENTITY_GRAPH_NAME = "entity"
TEMPORAL_GRAPH_NAME = "temporal"
CAUSAL_GRAPH_NAME = "causal"
